### PR TITLE
add nuget

### PR DESCRIPTION
**Pull request by danmoseley**
this seems like the right place? (assuming you run in production using appsettings.Development.json?)

I didn't test it. 😃 

cc @aortiz-msft  after this is done, you can mark bugs for tactics with a label named "servicing-consider" and they will appear in https://tacticsview.azurewebsites.net/. No emails required.

cc @leecow

### CODE REVIEW

**Comment by danmoseley** [comment]
cc @timheuer

**Comment by timheuer** [comment]
This is added (this isn't the right place as this is onyl for dev but needs to be on Azure config).  `nuget/nuget.client` was added.  Please note though TacticsView shows *Pull Requests* that are tagged, not just issues, so it needs to be a pull request

**Comment by danmoseley** [comment]
Cool, thanks @aortiz-msft FYI, yes I should have clarified it's PR's that are tagged. tactics doesn't look at issues at all.

**Comment by timheuer** [comment]
Also FYI @danmoseley @aortiz-msft the nuget/nuget.client repo was already being tracked.  My guess it was the pull request aspect that maybe folks didn't know about.  Also I modified the About link to show what repos are currently being tracked https://tacticsview.azurewebsites.net/about will now list which ones are being tracked.

**Comment by danmoseley** [comment]
ah. great.
@aortiz-msft if you experimentally add "servicing-approved" to eg https://github.com/NuGet/NuGet.Client/pull/5035 you should see it on  https://tacticsview.azurewebsites.net/servicing-approved

**Pull request closed without merging**
